### ISSUE TITLE
Several problems in new release 2.06-RC1

### ISSUE THREAD

**Issue by Jaroslaw1** [Ralim/ts100#424] opened 2018-12-31 23:43 UTC
Hi,
In installed the latest 2.06-RC1 firmware onto my TS100. Appears several issues:

- when I enable the iron, it shows only "305C"
- when I go to options flickering vertical bar on the ride side in LCD [checked in english language]
- it appears often shows "TIP IS DISCONNECTED" [checked in 2 new soldering tip]
- calibrate temperature is not posible, all the time shows 001C-003C

Thank You for firmware. Promises to be very good. Include new feautures but must be corrected. Im waiting to new release.

Rev. 2.05.1 is good and stable

Regards, sorry for my english

**Comment by Ralim** [comment] 2018-12-31 23:57
Duplicate of #422 
Im working on trying to find the cause of some of these

**Closed by Ralim** 2018-12-31 23:57 UTC
