### ISSUE TITLE
Temperature calibration expert mode

### ISSUE THREAD

**Issue by Matatu** [Ralim/ts100#351] opened 2018-09-01 22:49 UTC
* **I'm submitting a ...**
  - [ ] Bug report
  - [ x] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
Feature, it would be nice to have an additional "expert mode" for the temperature calibration. This mode should deal with real values (like the voltage calibration) instead of extrapolate from ambient temperature. For a few bucks you can buy a Hakko FG-100 copy, which can measure the tip temperature directly.

**Comment by Ralim** [comment] 2018-09-02 10:00
Hi, Closing this as its a duplicate of #303 
Work is on going on this already, Just haven't had time to sit and polish and test it fully yet.

**Closed by Ralim** 2018-09-02 10:00 UTC
