### ISSUE TITLE
Various new bugs with the latest 2.06 firmware on a ts100

### ISSUE THREAD

**Issue by sefer2** [Ralim/ts100#422] opened 2018-12-29 06:59 UTC
Hi,

In installed the latest 2.06 firmware onto my ts100. I upgraded from the official 2.18 firmware.
The first thing I noticed is that the main screen flickers twice before settles whenever the solder iron is plugged into power.

Next, entering "Advanced Options" there's a checkbox square to the right of "Detailed idle screen", its right most edge flickers all the time. In fact, this appears to happen with all the items that draw the right-most column on the screen.

Lastly, when I enable the iron, it shows only "305C" (it does heat up, but the screen displays a constant 305C, not showing the current temperature) and no warming/cooling progression. I have no idea when it reached its final designated temperature.

I tried doing a factory reset (I hope I did it correctly) without any effect.

**Comment by federck** [comment] 2018-12-29 10:47
Also I was able to find that:
-The writings in "Tip Model" option are overlapping.
-"Advanced calibration" and "Simple calibration" are not shown in the menu.
-If you set a "boost" temperature near to the maximum limit of temperature and then, during soldering, you activate the "boost mode", the message "bad tip" will be shown.
The question is: would be better reduce the overshoot or maybe reduce maximum temperature depending on the tip model?

Thanks,
Federico

**Comment by iLLiac4** [comment] 2018-12-31 04:35
I have also tested the new firmware and besides the bugs above there is also screen tearing when text is scrolling.
I really like the thermal mass of the tip and would it be possible to implement with the tip model also a small icon of the tip or. is it overkill?
[https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiJ3sa8nsnfAhVH3qQKHTr9AqYQjRx6BAgBEAU&url=%2Furl%3Fsa%3Di%26source%3Dimages%26cd%3D%26ved%3D%26url%3Dhttps%253A%252F%252Fwww.renaissancerobotics.com%252FTS100tips.html%26psig%3DAOvVaw0plRK6XFn0V_aJzxfrF3db%26ust%3D1546316437145929&psig=AOvVaw0plRK6XFn0V_aJzxfrF3db&ust=1546316437145929]

**Comment by Ralim** [comment] 2018-12-31 04:52
[TS100A_2_6_AtollicBuild.zip](https://github.com/Ralim/ts100/files/2717736/TS100A_2_6_AtollicBuild.zip)
Any chance you could give the above build a shot?
Its build using my local machine rather than linux and want to narrow down if this is a compiler issue or not.

@sefer2 I cant reproduce locally the flickering much, can you see if the above build is better or worse?

@federck The text running into each is interesting ,what language are you running? This is most likely a language related issue (I only test EN here usually).
Advanced calibration is only shown when its a user tuned tip, not when you select a preset.
Do you mean the temperature on the screen doesnt show fluctuations or that its not showing live data at all ? When your using it with the new PID the tip temperature fluctuations are reduced considerably.
This new build has a slightly lower cap to try and reduce the ADC bad tip protection, i might re-work that more in a day or two.

@iLLiac4 Basically out of room at the moment to fit any :( (some builds are down to single digit free bytes in the binary). If someone (me or others) impliements compile time font generation we could free up some room for more graphics.

**Comment by iLLiac4** [comment] 2018-12-31 08:39
Have tried it and the flickering seems to be gone.
There is still bad tib if boost mode is selected.
And also new bug that turns off the soldering iron if you do not select detailed soldering info under advanced settings.

**Comment by federck** [comment] 2018-12-31 10:50
Well, I think that the italian release, like other releases using a certain number of characters, it's affected by the problem just because text isn't drawn in the most right part of the screen.
![jamm](https://user-images.githubusercontent.com/33298498/50558266-bfba8d00-0cec-11e9-9e06-62099c90528f.jpg)

Yes, I meant live data as @sefer2 did, but that's a problem circumscribed only to graphical interface.
However, in your newest relaese, soldering mode (using GUI) leads to the reboot/freeze of the iron.

Thanks for the other clarifications!

**Comment by Jaroslaw1** [comment] 2019-01-01 17:55
Calibrate temperature still not working. Only i have this problem :) ? When calibrating is done appear: "calibrate tip offset". Temperature showing in menu 005C. Temperature on my room is 23C. Please see video. Thanks and good luck
![dsc_0062](https://user-images.githubusercontent.com/35426899/50575109-c8978580-0df6-11e9-8f50-cb51f904f951.JPG)

https://youtu.be/2yat2SqHzoQ

**Comment by sefer2** [comment] 2019-01-01 19:41
The latest build seems to solve most of these issues I've encountered, with the exception for the double blink when the power is plugged in. I no longer see the flickering with this build.
Great work Ralim! Thank you for a fantastic firmware!

**Comment by Jaroslaw1** [comment] 2019-01-01 21:44
@sefer2 You don't have problem temperature calibration? Maybe I'm doing something wrong?

**Comment by sefer2** [comment] 2019-01-02 04:01
I didn't try that, most of  the original problems I reported appear to be solved though.

**Comment by Ralim** [comment] 2019-01-02 05:12
@Jaroslaw1 Interesting to hear the temp isnt fixed, I'll look at this shortly. Honestly was focusing on other bugs. The temp issue is known about, and its mostly a UI thing, the tip tracks fairly accurately (on my units).

**Comment by Jaroslaw1** [comment] 2019-01-02 07:52
Hey,

Before calibration temperature in main menu is ~15°C, 8°C less than the temperature in the room. After calibration is ~003°C. When i begin soldering, temperature 160°C it melts the tin [solder]. In ver-2.05.1 temp. after calibration is correct. Otherwise everything is fine [best firmware ever!].

Thanks for your work and Regards

**Comment by iLLiac4** [comment] 2019-01-02 10:36
I have tested calibration and it really does not work. When calibrating it sets to around 0 when at room temperature.

**Comment by federck** [comment] 2019-01-02 14:13
"Simple calibration" and "Advanced calibration" show "Detailed Idle screen" description.

**Comment by mixxxlalex** [comment] 2019-01-04 07:44
Hello. I tried the version v2.06-RC2. In it, as in version v2.05.01, Russian letters are displayed incorrectly. Is there any way to fix this?

**Comment by RustyWraith** [comment] 2019-01-09 16:14
> @sefer2 You don't have problem temperature calibration? Maybe I'm doing something wrong?

I can confirm the problem on ts80. Room temp is 0 degrees after a calibration.

**Comment by ElenaPower** [comment] 2019-01-10 18:38
I can confirm 0°C at room temperature after calibration on my TS100.

**Comment by Cherenkov11** [comment] 2019-01-10 23:15
Yes, same bug, after you do the calibration shows ~0 C, and for me I checked the temperature at 300 set, and the external thermocouple shows around 325 C, so a little bit of overshoot. (B2 tip)

**Comment by csdpm** [comment] 2019-01-11 20:58
V2.06 RC2:
- Yes, I see the ~0'C tip temperature at ambient.
- L/R swapped on display orientation
- Cooldown blink not working (simple soldering screen, detailed idle screen)
- Boost and Standby temps appear to track the operating tip temp as it is adjusted up and down.

Apart from that, it's a great usable release.

**Comment by iLLiac4** [comment] 2019-01-12 16:06
Today I have got a new TS100 with PCB v2 and the rotation of the screen for left and right handed is acting strange. It tilst too fast in right hand position (i am left handed). Can this be tweaked?
On the other TS100 with PCB v1 it works as it should.

**Comment by bakerenko** [comment] 2019-01-23 07:10
No russian language, please fix.

**Comment by Brassee** [comment] 2019-01-25 22:18
> V2.06 RC2:
> 
> * Yes, I see the ~0'C tip temperature at ambient.
> * L/R swapped on display orientation
> * Cooldown blink not working (simple soldering screen, detailed idle screen)
> * Boost and Standby temps appear to track the operating tip temp as it is adjusted up and down.
> 
> Apart from that, it's a great usable release.

Same here

**Comment by Nazosan** [comment] 2019-01-28 09:45
So I just tried this update from a few hours ago on my TS80 and now it won't even turn on.  The only function that works is flash mode by holding + while plugging it in.

**Comment by iLLiac4** [comment] 2019-01-28 09:56
Same on TS100. Does not power on after RC3. Only DFU works so have downgraded to latest available online.

**Comment by bradanlane** [comment] 2019-01-28 10:33
I have a TS80 which came with the USB-C cable and a 9V 2A power supply. The TS80 shows 18W on the status screen. When I use a 5V 2.1A source ithe TS80 only shows between 5W and 5.3W. I’ve trated several wall chargers and USB batteries with a 2.1A output.

**Comment by Nazosan** [comment] 2019-01-28 10:53
The TS80 isn't supposed to really use 5V at all except for the USB connection.  I think also 5V 2.1A chargers expect the device to do something or other to indicate a larger current is safe and fall back to 1A max otherwise (which would be consistent with the results you got.)  Official documentation and specifications explicitly state 9V 2A via QC 3.0 is the only thing it supports.


BTW, I was getting 3C for my tip temperature when it was at room temperature before too on my TS80 even after calibration.  It didn't seem to be that big of a deal since heat mode seemed accurate enough, but anyway, TS80 was doing it too.

**Comment by whitehoose** [comment] 2019-01-28 12:51
bradanlane
Nazosan is correct, the iron is QC3  Withour negotiation the default is 5v, and mine will sit at the menu screen quite happily on 5v - but as soon as the iron starts working it negotiates more volts and heats up using 8 or 9v.
The stock 1.06 would give a low volts error as soon as a button was pressed if connected to USB2
I first came to Ralim looking for f/w that would allow me 5v working (just in case).  But the bugbear is this is (almost) exclusively a QC device - and to make it worse - it can be very picky about which QC it will and wont work with.  If you buy a power brick ... or even a wallwart do your homework and be sure other people are using that model with the 80 too.  You can't even be certain that even a manufacturer is good ... you need to be model specific.

Xiaomi MI 2 - 10000 mAh Power Bank works (I think the 20000 works too - but you need to ask that question).
Search ebay
QC3.0 QC2.0 USB DC-DC Buck Converter Charging Step Down Module 6-32V 9V 12V J6N1 works but needs a 12v source so it has something to step down.  I've combined it with a step up/down buck/boost converter so any source above 3.6v can be boosted to 12v or more to provide enough to get the Iron working
And the DS.OX wall wart that comes with the Iron's "extras" works.
The ISDT BattGo BG-8S Smart Battery Checker Balancer has a QC3 output - and that works too.

If you look through https://github.com/Ralim/ts100/issues/349 there are plenty of other suggestions that work.

**Comment by bradanlane** [comment] 2019-01-28 12:58
whitehoose - thanks for background and issue reference. I wanted 5V support for emergency/backup. I have plenty of USB2 batteries which work - albeit slowly. If I opt for a new battery, I’ll het one of the USB-C models with proper voltage and wattage.

**Comment by whitehoose** [comment] 2019-01-28 18:06
Didn't make that clear .. the compatibility issues are with the USB-c models (QC3).  The standard USB2 models only sort of work depending on the firmware you are using.  The firmware that came with the iron originally didn't work past the first menu screen on USB2 a quite early version of Ralim's firmware did ...

If (when) you go for USBc - do that research - the QC3 "standard" is anything but standard.

**Comment by ElenaPower** [comment] 2019-01-28 20:58
V2.06-RC3 does not work for me. Only black screen.

**Comment by Brassee** [comment] 2019-01-29 12:24
TS100, EN V2.06-RC3, nothing on screen

**Comment by asymcon** [comment] 2019-01-29 15:31
My TS80 does this with 2.06RC2 using QC3:
[VID_20190129_162500.zip](https://github.com/Ralim/ts100/files/2808346/VID_20190129_162500.zip)
Is this voltage pulsating behavior normal? Also it negotiated for 12V even on 18W setting.

**Comment by asymcon** [comment] 2019-01-29 15:42
> So I just tried this RC3 update from a few hours ago on my TS80 and now it won't even turn on. The only function that works is flash mode by holding + while plugging it in.
> 
> A previous one (I think RC2? EDIT: probably RC1) worked fine. Unfortunately previous TS80 files are gone now so I can't downgrade. I didn't realize I should keep backups.
> 
> EDIT: Side note, I just bought a new power supply. It is much higher quality than the one that shipped with my TS80. It is capable of a very high wattage -- 40 something I think -- though of course still the standard 2 amps at 9V via the normal USB 3 port (can QC actually do 2.66 to get 24W or isn't that PD only? I don't really need 24W, I just wanted something better quality that I could be 100% sure would handle the 9V 2A with room to spare.) I mostly did this because the stock one seemed really cheap and some component smelled like it had gotten too hot to me. Anyway, with the version of this custom firmware I was using before this would not work. While heating up it would shut off and reset every time I tried it. I assumed the power supply was faulty. On a whim I tried it with the stock firmware (which I'm now having to use since the custom firmware doesn't boot and I must say that it's definitely much clunkier to actually do the simplest things) and it works fine. Voltage goes down a tiny bit (8.57V while heating) then stabilizes at 9.03V once completed. At this point I wonder if there is anything at all wrong with the plug after all or if it isn't something specific to the custom firmware. I really don't like the stock firmware, but I'd feel more confident using this presumably much higher quality power supply. Does it just not like the lower voltage? Seems to work fine though. It still heats up very fast and holds steady.

Here, I made a backup (sorry @Ralim ):
[TS80_EN.zip](https://github.com/Ralim/ts100/files/2808401/TS80_EN.zip)

**Comment by Nazosan** [comment] 2019-01-29 18:42
Thanks.  Is that RC2?  I'm wondering about the above user's description of voltage issues and it does say something about voltage oscillation while heating.  I wonder if that might be kind of harmful to the iron.  I'm sort of inclined to stick with the stock one even though I kind of hate it (in particular the fact they didn't switch the buttons in left handed mode drives me nuts.)  The fact it seems to give such consistent voltage and works with what has to be a better quality power supply makes me think I would be better off waiting for another version anyway.

**Comment by asymcon** [comment] 2019-01-29 19:00
> Is that RC2?

Yes

> voltage oscillation while heating

Only on 24W and only on QC3.

**Comment by FiveOhCS** [comment] 2019-01-29 22:08
I don't get any activity at all on 2.06 RC3. No flickering or anything. 

Reverted to 2.05 and it works fine.

**Comment by RustyWraith** [comment] 2019-01-29 22:20
No activity on TS_EN.hex from v2.06 RC3.

I cannot figure out how to compile/flash RC4.
Little help here?

**Comment by Ralim** [comment] 2019-01-30 03:56
@rozwell  @RustyWraith My apologies, hex files uploading now.

**Comment by Nazosan** [comment] 2019-01-30 05:18
This "RC4" build definitely works on my TS80.  Cool tip temperature shows correctly in this one too -- or at least really close (it was a few degrees above actual ambient, but I couldn't give a specific number.  Very close anyway.  Much closer than the 3C it said before.)  It still won't work with the (presumably) better power plug that the stock firmware will though.  Watching the voltage on the screen, it's going up and shuts off right as it hits 8.9V for some reason.

From what I'm understanding after trying to read up on the QC 3.0 "standard" is it seems like there are three voltage profiles.  3-6, 6.2-9, 9.2-12 at 3A, 2A, and 1.5A I think.  Is it possible it does something like trying to go to the next range as it hits 9 but fails or something?  I notice when I use the original charger it oscillates as high as 9.8V but never shuts off.  And it smells worse than ever (I think the one they sent with the TS80 really does not like that oscillation,) so I seriously don't trust it.

**Comment by Ralim** [comment] 2019-01-30 05:54
@Nazosan It sounds like your "nice" plug isnt rated for higher than 9V, can you confirm this?

In the 18W mode the iron measures the tip resistance and calculates the ideal voltage to meet the 1.5A.
What firmware language are you using? Ill make you one hard coded to 9V to test this theory with.

The features that will come in future firmware is to allow you to set 9V/12V or 18W/24W modes for the TS80. Just want to get the current features stable first :)

**Comment by Nazosan** [comment] 2019-01-30 06:03
I'm using the EN firmware.  This QC 3.0 charger can probably do 24W mode if that's somehow better.  I just thought a lower wattage setting would mean the iron is working less hard (I want this thing to last a long time.)

**Comment by rozwell** [comment] 2019-01-30 06:10
Flashed RC4 with TS100_EN.hex and it works - great job @Ralim ! :)
The only issue I can spot at this point is invalid tip (BC2) calibration temperature ~34°C, rather than real room temperature 21~23°C.
To confirm, I flashed to stock v2.18 and it showed ~21°C, then back to RC4 and got the results above. Every time with factory reset, just to be sure.

**Comment by Nazosan** [comment] 2019-01-30 07:04
Maybe a simpler solution might be if there was a manual override on tip calibration?  Is it linear?

**Comment by elgab** [comment] 2019-01-30 09:25
v2.06-RC4 flashed on TS100 PCB v2, and working fine.
1. auto rotation set to manual, auto mode is a bit dodgy but nobody is changing hands so...
2. on B2 stock tip i get 26 celsius after calibration, however the room is 21.
3. sleep working fine: 1 minute with 90 celsius.

**Comment by Trezona** [comment] 2019-01-30 09:42
Just flashed TS100_EN.hex v2.06-RC4, and all is working great now. Thanks @Ralim

**Comment by iLLiac4** [comment] 2019-01-30 10:02
Have tested RC4 and it works really good. On PCB v2 auto rotate for left hand is not as good as on v1.

**Comment by Ralim** [comment] 2019-01-30 10:32
@Nazosan Before you claim it can do 24W, double check it can do that in QC mode, a lot limit you to 1.5A in QC mode (even if PD mode is higher).. If it works at 2A.. Well thats up to you to want to test.

24W mode tells the iron to negotiate for a higher voltage than it calculates for 18W basically, to try and push more power through it. Some QC chargers are rated for 12V 2A, though not many. Most people use this to try and run the iron at 12V and to hope that their PSU copes with it :D

@rozwell When you do the "simple" calibration, its only as accurate as the temperature difference between the tip and the inside handle temp. If you want  to have a more accurate scale you can do the advanced calibration with a tip temperature sensor (such as the FG-100 clones).

The tip is roughly linear at higher temps, but a bit more non linear at room temperature, so most errors show up at low temps.

Also this upgrade reset the system settings, so you may want to leave the iron for an hour or two so that the handle and the tip are equal temps, and then perform the simple cal if your temp is offset, though 2-3 degC is better than a lot of other irons out there (1%)

Also when comparing stock to mine, its a completely different temperature compensation and lookup routine being used, my firmware goes for assuming a worst case cal value (slightly high) so that it works for TS100 and TS80, rather than a specific tuned value. 

If you go into the debug menu (hold the rear (B) button while on the idle screen, you can use the front (A) button to go through readouts, and one of these is Than, which is the temperature in the handle x10. This is the only way the iron can actually know the ambient temperature.

@elgab default of 320C is just a common value that is used a lot, since its trivial for anyone to adjust from that point.

I agree that rotation detection isnt ideal on V2 pcbs (TS80 is always a V2). The ST accelerometer does not give as many nice options for tuning rotation detection.

@vasyapupkinodin This is known as the Russian language files try to use Russian chars in the slots that are "one English char only". At some point this will be fixed to support non English characters in these slots.

**Comment by rozwell** [comment] 2019-01-30 17:34
@Ralim Thanks for the handle temp advice - tried calibration after whole night and it was off by only ~5°C.
I checked THan and it was at ~25°C, ambient 20°C so that's where the difference is coming from. From there it just gets higher, when handle warms up while it's powered up, or simply from body heat, resulting in a ~10°C+ difference in a very short time, without even working with the iron.
That gave me an idea for a quick workaround where I just heated up the tip for a few seconds, then used auto calibration to compensate the difference. That did the trick, not practical, but works. 
Looks like the handle temp offset is needed. Or is it already there?

@elgab +1 for default 250°C, much safer. But for now you can set it on USB power - it won't heat up because of undervoltage and when you hold button A, you can set desired temp.

**Comment by Ralim** [comment] 2019-01-30 22:35
@rozwell The thing is that we dont actually care what "ambient is" we only use the handle temperature for cold junction compensation of the thermocouple in the tip. 

The only time handle temp is used for anything other than cold junction calibration is when you do a calibration of the tip, which is why i recommend leaving the unit alone for an hour or two to let its temps stabilise. 

Changing the default setpoint is sort of a moot point since everyone is going to have their own preference, and for those few who dont change it, it wont be the deciding factor in tip damage usually. Tips are an expendable item eventually, so the choice is always yours about changing the temp.

**Comment by rozwell** [comment] 2019-01-31 04:19
@Ralim understood, seems just my unit shows a few degrees higher than it should. Not really important and relatively easy to compensate with the calibration trick I mentioned before.

Looks like it's time for me to finally start using TS100 with your awesome firmware :D

**Comment by Nazosan** [comment] 2019-02-13 02:38
Did you ever do the hardcoded voltage firmware?  I'm curious to try it.  I really do not like the stock firmware, but I'm just afraid to use the power plug they provided with it.

**Comment by Ralim** [comment] 2019-02-13 03:13
24W mode is 12V hard coded, next rev will have more options when i have some time to sit down and write it

**Comment by Nazosan** [comment] 2019-02-13 06:10
Oh, I'm sorry.  I completely misunderstood what you were saying before.  Hmm.  It has an interesting result with 24W mode.  It cuts off as the voltage is slowly rising when it hits ~9V or so, then if I try using it again it works without a problem, this time going up to 12V (where it seems to hold very steady at 12.0V with no oscillation btw.)  I understand it can accept higher voltages than 9V, but is 12V a strain on the TS80 long term?  The wattage rating says 29.7W while it's heating up though.  That's ind of strange.  Officially the type-a port (QC 3.0) only supports 1.5A at 12V.  The type-c (PD) port can do 2.3A at 12V, but that's 27.6W.  Is the TS80 reading it wrong?  The plug doesn't seem at all warm (compared to the plug that came with it getting quite hot even at 18W) but it seems like I smell something from it too.  Is that just a normal result from pushing such a high current through a power source like this?  (I'm curious if the QC 3.0 chargers that came with other people's TS80s were doing this.)

**Comment by Nazosan** [comment] 2019-03-05 01:55
So far the 24W mode seems to be ok, but sometimes for some reason it loses the higher voltage and drops to 5V (I think after sleeping for a while, but I'm not sure if that's the cause.)  It's trying to keep the tip temperature up, but ends up only able to maintain around 250C or so with only 5V.  I have to disconnect and reconnect it to get it back over 5V.

**Comment by bradanlane** [comment] 2019-03-05 09:15
I’ve seen the “stuck at 5V” issue with the 2.04 release on my TS80 and a standard 18W setting. I had the same workaround.

**Comment by Ralim** [comment] 2019-03-06 02:02
The stuck at 5V issue usually means that the QC negotiation failed. I've had this when a plug wasn't seated properly as the initial negotiation is only done once at start as its fairly slow.

**Comment by Nazosan** [comment] 2019-03-06 03:46
Yeah, I assumed that it was such a thing since 5V is presumably the default fallback, but why would it drop to 5V after that initial negotiation?  Does sleep mode actually go ahead and drop back to 5V then renegotiate?  Because if sleep mode continues at the full voltage and merely uses less current then presumably the voltage wouldn't change.  I was thinking maybe it was the plug itself, but I don't dare try running 24W mode to test on the original plug since it appears to be of exceptionally low quality and I'm still afraid to trust it for any length of time.

I did try switching back to 18W and switched back to the original plug, but oddly enough it seemed to keep turning off the heat.  I don't know if it was just resetting or simply disabling heat because it always happened while I was actually using the iron and I didn't know it until after I started having a lot of troubles with the solder and then looked at it.  I think maybe for now I'm going to give in and go back to the stock firmware even though it's really horrible to use (especially if you're left-handed since left-handed mode only switches the screen but not the buttons...)  I don't think the voltage dropped to 5V, but perhaps it did and that would explain it sort of "shutting off" there.  (It's worth noting that the higher quality plug I've been using does support a pretty significant amount of current at 5V.)


I believe the cable was well seated on both sides the entire time.

**Comment by omair94** [comment] 2019-03-11 15:59
I have noticed that when using the TS-80 with a QC 3.0 power bank, there is a faint buzzing noise coming from the power bank. I have tested it with 5 different power bank, all of which exhibit this. When using the included wall adapter, there is no buzzing. The buzzing only occurs on this firmware and not on the official firmware.

I'm not sure if this is actually an issue, but it is a bit concerning.

**Comment by VjyedSC0UFMc8z** [comment] 2019-03-28 14:37
This was so helpful. You have the only firmware that I could get to work with my QC3 power bank https://www.ravpower.com/download/ravpower-turbo-20100mah-power-bank-with-usb-c-and-qc-3.0.html 
All the rest wouldn't trigger the bank to provide power and heat up. 
The only critique I would have for this combo is that my power bank will sleep before any of the standby settings on the TS80. But it turns on, which is a huge improvement. 
Thank you!

**Comment by whitehoose** [comment] 2019-03-28 17:29
This was covered in some detail in the Mamoth ts80 thread (this is for ts100 which isn't really a qc3 candidate)  The QC3 "standard" has been reverse engineered and thus (literally) subjected to the chinese whispers syndrome.  It's always worth asking for powerbanks or adapters that are known to work (have a look here https://github.com/Ralim/ts100/issues/349 - it's been covered a few times)
The falling asleep issue has also been covered, to date the "best" solution (assuming you've tried any inbuilt measures the bank may have) is to either plug in a LED torch/lamp dongle or, if you're any good with a soldering iron o<}:oP  stick a resistor and LED on the end of a cut down usb lead yourself.  The additional constant load will do the trick.

**Comment by asymcon** [comment] 2019-03-28 20:12
Xiaomi Mi Pro powerbank has a special mode for charging low power devices which instead of its typical 30 second timeout, turns off after 4 hours.

**Comment by WerVa** [comment] 2019-04-15 21:37
Hi when 2.06 stable?

**Comment by hgpt** [comment] 2019-05-09 10:08
Just upgraded to v2.06-RC4 on my TS100 and "out of the box" without changing any setting the set temperature just when holding the iron in the hand it's all around the place. (I'm attaching a GIF with the bug). 
My setup is:
- TS100
- 24V 5A capable PS
- B2 tip

I've also

**Comment by torqu3e** [comment] 2019-05-30 15:02
TS100 doesn't get past 430c.

Sort of similar to the above issue.
2.06 RC4 TS100 BC2 20.1v power supply
Tip tracks up to 360 almost dead on then starts fluctuating from 370c onwards, a few degrees off at ~370 isn't a real concern for me but the iron not getting to 450 is weird. It gets to 420ish or hovers around 430 max.

I'd gladly provide any debugging info or power meter data if that'll help with this.

**Comment by jrrech** [comment] 2019-06-12 02:04
Just flashed 2.06 RC4 into my TS80, and the results with both QC adapters I own are pretty much the same: almost everytime the TS80 is plugged in it gets stuck at 5V, but unplugging the power supply and plugging it back sometimes make the TS80 negotiate higher voltages and work as expected.

The adapters I tested were a Motorola SC-28 (15W) and the Blitzwolf BW-S9 (18W QC 3.0). Both work properly with the stock 1.07 firmware.

**Comment by Nazosan** [comment] 2019-07-14 03:20
So I noticed the new RC5 out and thought I'd try it just to see if it helps any with the problems I've had so far.  For some reason it won't flash though.  I even tried doing a factory reset.  I also tried deleting the existing files on the virtual drive it presents just to be sure (since it adds extra stuff like "System Volume Information" and ".trashes" and I know it doesn't need "System Volume Information" since that is Windows' doing.)  I noticed that the TS80_EN.NOT file differs from the TS80_EN.bin from the update, so in the off chance it has anything useful in there like debug data or whatever I've included it.
[TS80_EN.NOT.zip](https://github.com/Ralim/ts100/files/3389425/TS80_EN.NOT.zip)

**Comment by Ralim** [comment] 2019-07-16 00:10
@Nazosan 

Flashing issues generally dont belong in these threads.
Almost always the issue is the miniware bootloader.
You could try another PC, make sure no AV is running or any other software that tries to watch file open events. Also make sure you are doing the double-copy trick.
The bootloader actually creates fake entries for those folders to stop the OS making them, as they take the first file copy to be the "firmware"
Make sure you are using the .hex file to update with the miniware bootloader! having a .NOT usually means the file format is wrong.

**Comment by Nazosan** [comment] 2019-07-16 03:36
Ah, up to now pretty much every release has said to post about problems in this thread.  I thought it was a problem with the firmware.  Seems it wasn't.  I was indeed flashing the wrong file.  I successfully flashed this latest firmware and it does seem like it overall works better because I am able to use the 9V setting.  It has a few oddities though.  It's reporting power usage as high as a little over 90 watts when initially heating up and it shows as "low" as 58 and as high as 78 for power while maintaining tip temperature.  It seems like it doesn't maintain quite as well since it drops about 10C at first when I use it and power usage goes way down from that "58-78" to as low as 0.01.  Most of this seems to  be pretty much visual other than that, so overall this does seem to be a better working firmware given that the 9V setting works with power supplies it didn't like before.  (I'm actually really happy about that.)

**Comment by yzept** [comment] 2019-07-28 08:06
RC 5 has some interesting new bugs. RC 4 worked very well with a Digitec QC 3 Battery Bank selecting 12v or 9v as set in the UI but the RC 5 revision seems stuck at selecting 9V. Power readings show imaginatively high up to 96W and fluctuate rapidly. RC 4 would vary the QC 3 supply voltage seemingly as power requirements changed but RC 5 seems to stick at 9v. For Me with this battery bank RC 5 is not useable.

**Comment by Ralim** [comment] 2019-07-29 07:47
@yzept
RC 5 changed from using 9V and then jumping up to 12V in 0.2V hops to negotiating for 12V as per the spec. Interesting to know your charger does not support this. This can be reverted fairly easily.

The auto-adjusting power supply voltage was removed as it generally made the tip temperature more unstable and created a 3-5 second oscillation that wouldn't damp out, and causes fussy power banks to shut off from over voltage occasionally.

The power readings are known bad and will be fixed when I'm next looking at it.

**Comment by Nazosan** [comment] 2019-07-29 21:40
I'll have to second that removing the dynamic voltage change isn't a bug.  I've had those issues with multiple power supplies really.  This latest one is far more stable, including with my own QC battery power bank.

The wattage display bug definitely isn't a major issue, though it sure is weird watching my iron insist it's using so much power that both it and the PSU would surely burn out in an instant.  Actually, I've been wondering in that respect:  does it really need to show the actual wattage?  Might it not be better if it only showed the current and voltage instead?  That's usually all that really matters anyway.  I know you can calculate it from the wattage, but it seems unnecessary and more useful to know the current directly.

**Comment by dhiltonp** [comment] 2019-07-29 23:06
The wattage is based on voltage, duty cycle and estimated resistance.

@ralimtech: we could easily display a rolling average instead of
instantaneous temperature (and maybe wattage?) The temp rolling average is
already calculated, I don't remember on wattage...

**Comment by Ralim** [comment] 2019-07-30 01:54
@dhiltonp 
I added in a small rolling average on the temperature on screen in this release to make it more readable. Could definitely add another one to the wattage if its not there.

Also when you have a chance @dhiltonp, I was running into issues getting a stable PID control working for the TS80, and open to ideas around the best way to stabilise it. Mostly running into the classing oscillation vs response time problems.

**Comment by dhiltonp** [comment] 2019-07-30 03:27
The history class is a ring buffer with 3 operations: update, dereference (`[]`), and average. On every update, the old value is subtracted and the new value is added to a rolling sum, so the average step is one division operation.

The watt display currently uses milliWattHistory[0], the most recent value. Changing it to .average() would show the average over the last 3.5 seconds, the period over which we dampen oscillations (see more at the bottom).

https://github.com/Ralim/ts100/blob/master/workspace/TS100/src/main.cpp#L567 is one of the lines that would need to be changed.

----------------

For oscillation in this case, I'd first fix the wattage estimation. 

We use our calculated wattage and the thermal mass to compute a duty cycle. If the calculated wattage is 5x too high, it's the equivalent of inputting a thermal mass 5x too low!

That's just an educated guess - I don't have a TS80 and haven't seen these issues first-hand.

-----------------

We average over `oscillationPeriod` for our `I` term. It is pretty forgiving, but should be greater than 1/2 the actual period. It's currently set to 3.5*hz. Larger values may help with stability, but will hurt responsiveness and use more ram. `history.hpp` would need to be modified to handle buffers larger than 127 values, too - [size+loc or i are uint_8t, and could overflow](https://github.com/Ralim/ts100/blob/aa51dc4dbe8612de1d8f40c46682418c8df4ab14/workspace/TS100/inc/history.hpp#L23). If you're seeing oscillation over periods >5-6 seconds, that could be the culprit.

**Comment by dhiltonp** [comment] 2019-08-01 01:03
In short: when the detected resistance is off, the derived wattage is off, so the PID controller is off, as it "thinks" in terms of wattage.

**Comment by dhiltonp** [comment] 2019-08-01 01:07
It needs to think it terms of wattage, because a 50% duty cycle means something completely different when powered by 9v vs 20v.

**Closed** 2019-12-29 05:44 UTC

**Comment by yzept** [comment] 2019-12-29 08:07
Hi Ben, thanks for getting it out!
It works for me except on my Digitech 20000mAh Battery Bank where it never rises above 9V whatever the UI settings where with prior releases I would see 12V with much better performance. The temperature measured with a Hakko FG100 thermocouple is now significantly more accurate. I will go back to the previous release to get the powwaaaaahh!
Thanks Again, Roger
