### ISSUE TITLE
Bad temperature compared to the stock firmware

### ISSUE THREAD

**Issue by Cherenkov11** [Ralim/ts100#337] opened 2018-07-27 00:59 UTC
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **Do you want to request a *feature* or report a *bug*?**
A bug related to bad temperature control of Ralim firmware

* **What is the current behavior?**
Well, as soon as I got my TS100 I flashed this firmware without trying the stock one, but, when I measured the temperature of the tip I got disappointed, even doing the calibration at room temperature nothing changed. So, I flashed the original firmware and I got the following results:

Set          Stock          Ralim
300          295             272
350          340             318
400          385             352

Note: I also did the automatic calibration on the stock firmware by the way and with the same tips TS-B2, TS-C1 with almost same results.

* **What is the expected behavior?**

We all expected an accurate temperature control. I do not know if it is something related to the PID controller or the calibration system. I know that there is a proposal to modify the PID, but I wanted to share my mesurments with my tips.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

***Steps to reproduce:***

1. Introduce the tip
2. Calibrate to room temperature
3. Set the temperature and measure it

* **What are you running:**

On the idle screen, you can hold the settings button and it will show you the firmware version.

  - Firmware Version: V2.05 May 7 2018
  - PCB Version: PCB2
  - Power Supply (Voltage and Current Rating) : 19V 3.42A

**Comment by Ralim** [comment] 2018-07-29 02:53
Duplicate of #303

**Closed by Ralim** 2018-07-29 02:53 UTC
