### ISSUE TITLE
starts into DFU

### ISSUE THREAD

**Issue by subzer0x** [Ralim/ts100#257] opened 2018-03-28 19:11 UTC
Im submitting a bug report. TS100 Only starts with USB connected, whenever I start with another power source it will only display DFU:3.43 but won't allow me to access any menu. When I start from USB I can access the menu but obviously don't have enough power for it to heat up. This happened after I patched it to the latest version

Thanks

Oliver

**Comment by JonnyFPV** [comment] 2018-03-28 19:38
Same for me. :( with previous version it freezes

**Comment by subzer0x** [comment] 2018-03-28 20:24
so its basically dead? factory reset wouldn't help either

**Comment by JonnyFPV** [comment] 2018-03-28 20:42
No, you can flash original firmware. It works. I hope ralim will fix that soon :)

**Comment by Ralim** [comment] 2018-03-29 10:49
This is a duplicate of #254

**Closed by Ralim** 2018-03-29 10:49 UTC
